2025-08-01 02:04:57,323 INFO    MainThread:1092351 [wandb_setup.py:_flush():80] Current SDK version is 0.21.0
2025-08-01 02:04:57,323 INFO    MainThread:1092351 [wandb_setup.py:_flush():80] Configure stats pid to 1092351
2025-08-01 02:04:57,323 INFO    MainThread:1092351 [wandb_setup.py:_flush():80] Loading settings from /root/.config/wandb/settings
2025-08-01 02:04:57,323 INFO    MainThread:1092351 [wandb_setup.py:_flush():80] Loading settings from /root/workspace/AIXueRLHF/wandb/settings
2025-08-01 02:04:57,323 INFO    MainThread:1092351 [wandb_setup.py:_flush():80] Loading settings from environment variables
2025-08-01 02:04:57,323 INFO    MainThread:1092351 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /root/workspace/AIXueRLHF/wandb/run-20250801_020457-w1oztule/logs/debug.log
2025-08-01 02:04:57,323 INFO    MainThread:1092351 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /root/workspace/AIXueRLHF/wandb/run-20250801_020457-w1oztule/logs/debug-internal.log
2025-08-01 02:04:57,323 INFO    MainThread:1092351 [wandb_init.py:init():830] calling init triggers
2025-08-01 02:04:57,323 INFO    MainThread:1092351 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-08-01 02:04:57,324 INFO    MainThread:1092351 [wandb_init.py:init():871] starting backend
2025-08-01 02:04:57,742 INFO    MainThread:1092351 [wandb_init.py:init():874] sending inform_init request
2025-08-01 02:04:57,749 INFO    MainThread:1092351 [wandb_init.py:init():882] backend started and connected
2025-08-01 02:04:57,750 INFO    MainThread:1092351 [wandb_init.py:init():953] updated telemetry
2025-08-01 02:04:57,756 INFO    MainThread:1092351 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-08-01 02:05:52,362 WARNING MainThread:1092351 [wandb_init.py:init():1610] [no run ID] interrupted
Traceback (most recent call last):
  File "/root/anaconda3/envs/aixue/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1606, in init
    return wi.init(run_settings, run_config, run_printer)
  File "/root/anaconda3/envs/aixue/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 996, in init
    result = wait_with_progress(
  File "/root/anaconda3/envs/aixue/lib/python3.10/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 24, in wait_with_progress
    return wait_all_with_progress(
  File "/root/anaconda3/envs/aixue/lib/python3.10/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 87, in wait_all_with_progress
    return asyncio_compat.run(progress_loop_with_timeout)
  File "/root/anaconda3/envs/aixue/lib/python3.10/site-packages/wandb/sdk/lib/asyncio_compat.py", line 30, in run
    return future.result()
  File "/root/anaconda3/envs/aixue/lib/python3.10/concurrent/futures/_base.py", line 453, in result
    self._condition.wait(timeout)
  File "/root/anaconda3/envs/aixue/lib/python3.10/threading.py", line 320, in wait
    waiter.acquire()
KeyboardInterrupt
2025-08-01 02:05:52,797 INFO    MsgRouterThr:1092351 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 2 handles.
